#+STARTUP: showall
#+OPTIONS: toc:nil

* flycheck-commit-check v0.1.0

  This is the flycheck-commit-check project. It is a [[http://flycheck.readthedocs.org/en/latest/][Flycheck]] checker
  that uses [[http://code.ryuslash.org/commit-check/about/][commit-check]] to provide syntax checking for git commit
  messages.

  The code can be found in ~flycheck-commit-check.el~ in the project
  source tree.

** Installation

   As with all Emacs packages installation can be done in a number of
   ways. The only dependencies it has are flycheck and
   [[https://github.com/magit/git-modes][git-commit-mode]].

   You must, of course, also have commit-check installed on your
   system and available in your =PATH=.

*** Manual installation

    If you don't (yet) use the Emacs package manager you can install
    it manually by downloading the code somewhere, adding the path to
    your =load-path= and either =require=-ing or =eval-after-load=-ing the
    package, like so:

    #+BEGIN_SRC emacs-lisp
      (add-to-list 'load-path "/path/to/flycheck-commit-message")

      ;;; Option 1
      (require 'flycheck-commit-check)

      ;;; Option 2
      (eval-after-load 'flycheck
        `(require 'flycheck-commit-check))

      ;;; Option 3 --- Only for Emacs 24 and up
      (with-eval-after-load 'flycheck
        (require 'flycheck-commit-check))
    #+END_SRC

*** Installation with package manager

    To install this package with the Emacs package manager, download
    the ~flycheck-commit-message.el~ file and call =package-install-file=
    and then pick the downloaded file. Afterwards you should add
    something like the following to your Emacs init file:

    #+BEGIN_SRC emacs-lisp
      (eval-after-load 'flycheck
        (require 'flycheck-commit-check))
    #+END_SRC

** Usage

   After installing the package you will have to setup flycheck for
   git commits, which is easy:

   #+BEGIN_SRC emacs-lisp
     (add-hook 'git-commit-mode-hook #'flycheck-mode)
   #+END_SRC

** License

   This project is licensed under the GNU GPLv3, its terms and
   conditions can be found in the file =COPYING= in the project source
   tree.
